import DocumentosModel from "./documentos.model";
import EmpresaModel from "./empresa.model"

export default class EquipamentoModel {
  constructor(
    public id: number = null,
    public tagEquipamento: string = '',
    public descricao: string = '',
    public localizacao: string = '',
    public categoria: string = '',
    public condicao: string = '',
    public tipoEquipamento: string = '',
    public inspecaoExterna: Date = null,
    public inspecaoInterna: Date = null,
    public proximaInspecaoExterna: Date = null,
    public proximaInspecaoInterna: Date = null,
    public placaIndentificacao: string = '',
    public valvulaSeguranca: string = '',
    public indicadorPressao: string = '',
    public pmta: string = '',
    public anoCadastro: string = '',
    public observacao: string = '',
    public numLacre: string = '',
    public dataCalibracao: Date = null,
    public proximaCalibracao: Date = null,
    public roscaConexao: string = '',
    public marcaModelo: string = '',
    public instrumento: string = '',
    public escala: string = '',
    public unidadeMedida: string = '',
    public tamanho: string = '',
    public bitola: string = '',
    public setPoint: string = '',
    public unidadeAjuste: string = '',
    public status: string = '',
    public possuiRgi: string = '',
    public fluido: string = '',
    public numRelatorio: string = '',
    public laudoValSeguranca: string = '',
    public numSerie: string = '',
    public capacidade: string = '',
    public norma: string = '',
    public inspecao: Date = null,
    public proximaInspecao : Date = null,
    public empresa: EmpresaModel[],
    public documentos: DocumentosModel[],
    public observacaoRgi: string = ''
   ) {}
}