version: '3.4'

services:
  fminspecao:
    image: josiassxz/fminspect-front
    build: .
    ports:
      - 8081:80
    extra_hosts:
      - "host.docker.internal:host-gateway" # Mapeia host.docker.internal para o gateway da máquina host
